### ISSUE TITLE
Please don't use global variables!

### ISSUE THREAD

**Issue by vitalk** [amialiashkasashka/leverx_task3#1]
https://github.com/amialiashkasashka/leverx_task3/blob/e7fcd8ff37fe93b4a16e260b27a509fda62c7aaa/task3.py#L10

**Comment by amialiashkasashka** [comment]
To be honest, it was the first thing i noticed, but then i thought that it`s not the reason of incorrect work and skipped. But ok, fixed. A bit slower now(( Maybe any other ways to do this without lose in speed?
